### ISSUE TITLE
Consider aligning API with p-limit

### ISSUE THREAD

**Issue by richardscarrott** [sindresorhus/p-throttle#16]
I really like the design of the [`p-limit`](https://github.com/sindresorhus/p-limit#readme) API whereby you create a limiter and pass in a `fn` as an argument e.g.

```js
const limiter = pLimit(3);
const result1 = limiter(() => doSomething(1));
const result2 = limiter(() => doSomething(2));
const result3 = limiter(() => doSomethingElse(3)); // Doesn't care about what the fn does
```

I wondered if you'd be interested in aligning `p-throttle` with `p-limit`?

**Comment by sindresorhus** [comment]
Good idea! PR welcome for this.

I think we should also take the opportunity to improve the readability of the API by using an options-object for the `limit` and `interval`.

---

To whomever decides to work on this, don't forget to also document how the existing behavior can be solved with the new API:

```js
const throttled = pThrottle(2, 1000)(index => { … });
```
