### ISSUE TITLE
Temporary disable throttle

### ISSUE THREAD

**Issue by sm2017** [sindresorhus/p-throttle#18]
Is it possible to disable throttle for a specific call?

```js
const pThrottle = require('p-throttle');

const now = Date.now();

const throttled = pThrottle(index => {
	const secDiff = ((Date.now() - now) / 1000).toFixed();

	if (index===4){
		return pThrottle.immediate(Promise.resolve(`${index}: ${secDiff}s`));
	}

	return Promise.resolve(`${index}: ${secDiff}s`);
}, 2, 1000);

for (let i = 1; i <= 6; i++) {
	throttled(i).then(console.log);
}

//=> 1: 0s
//=> 2: 0s
//=> 3: 1s
//=> 4: 1s
//=> 5: 1s
//=> 6: 2s
```

You can see that 5th immediately executed

**Comment by sm2017** [comment]
@sindresorhus Can you please reply?

**Comment by sm2017** [comment]
@sindresorhus can you please reply?

**Comment by sindresorhus** [comment]
Not currently possible, but I can see how that could be useful. PR welcome for something like `p.Throttle.bypassThrottling()`.

**Comment by Richienb** [comment]
How about we add an `isEnabled` property to the throttled function.

**Comment by sindresorhus** [comment]
> isEnabled

👍

**Comment by Richienb** [comment]
Also, what would `pThrottle.bypassThrottling(value)` return?

**Comment by sindresorhus** [comment]
With https://github.com/sindresorhus/p-throttle/pull/22 and `.isEnabled`, I'm not sure if `pThrottle.bypassThrottling(value)` is actually needed.

**Comment by sm2017** [comment]
> We could also add an `isEnabled` or `isThrottled` property to the throttled function to allow it to be disabled from the outside as well.

Can you please show an example? how `isEnabled` can works?! `const throttled = pThrottle(fn, limit, interval);` the `throttled` value is `const` and `pThrottle` return **a** function it cannot return multiple value, so how `isEnabled` can be works?!

**Comment by sm2017** [comment]
@sindresorhus I think `pThrottle.bypassThrottling(value)` is more powerfull, I have no idea about `isEnabled`

Consider an abstraction layer for throttling, it can be a parent class that implemented some  throttling and run the `runTask` method, in the child class we only want to override `runTask` and if we want to disable temporary throttling for a specific task (i.e. we have a cache in local storage and throttling is not needed) we can return `bypassThrottling`

**Comment by Richienb** [comment]
> Can you please show an example?

```js
const throttled = pThrottle({...})(async () => {...})

// Disable throttling
throttled.isEnabled = false
```

**Comment by sm2017** [comment]
@Richienb I think its a bad idea!! assume we want to throttle 100 times per second, and without throttling we can run tasks 10k per seconds
If you want to disable throttling just for a task and set `throttled.isEnabled = false` how you can re-enable it, it is very hard to do it
In the time of switching isEnabled to false and true, many other tasks will be run without throttling, You have no control to just run **a task** without throttling

**Comment by sindresorhus** [comment]
@sm2017 Thanks for elaborating. You're right, it makes sense to have `bypassThrottling`.

**Comment by Richienb** [comment]
> @sm2017 Thanks for elaborating. You're right, it makes sense to have `bypassThrottling`.

Back to the question,

> Also, what would `pThrottle.bypassThrottling(value)` return?

**Comment by sm2017** [comment]
@Richienb we want to skip throttling for index 4

```js
const pThrottle = require('p-throttle');

const now = Date.now();

const throttled = pThrottle(index => {
	const secDiff = ((Date.now() - now) / 1000).toFixed();

	if (index===4){
		return pThrottle.bypassThrottling(Promise.resolve(`${index}: ${secDiff}s`));
	}

	return Promise.resolve(`${index}: ${secDiff}s`);
}, 2, 1000);

for (let i = 1; i <= 6; i++) {
	throttled(i).then(console.log);
}
```

As you can see it just wrap a value and return the wrapped value

**Comment by Richienb** [comment]
> its somehow recognizable . i.e returnedValue instanceof BypassedPromise or returnedValue?.isBypassedThrottling

Perhaps we can create a class and give it the value that is normally returned.

Ideally, we would return a `Symbol` and (somehow) encode information in it.

@sindresorhus What do you think?

**Comment by sindresorhus** [comment]
I think a `class` wrapper is a good way to handle this.

A symbol would also be possible, by returning an object with the Symbol as the only key, but I think a `class` is better as we can just do a `instanceof` check.

**Comment by Richienb** [comment]
When trying to implement this, I realised that `pThrottle.bypassThrottling` doesn't actually make sense.

`p-throttle` runs functions after a delay so whatever a function returns is propagated immediately. Unfortunately, implementing `pThrottle.bypassThrottling` is actually impossible since it is defining a return value within the function itself that is throttled.

**Comment by sindresorhus** [comment]
Good point. It cannot be done from the inside. Maybe from the outside then. Something like this:

```js
const pThrottle = require('p-throttle');

const now = Date.now();

const throttled = pThrottle(index => {
	const secDiff = ((Date.now() - now) / 1000).toFixed();
	return Promise.resolve(`${index}: ${secDiff}s`);
}, 2, 1000);

for (let i = 1; i <= 6; i++) {
	throttled(i, {bypassThrottling: i === 4}).then(console.log);
}
```

@sm2017 Would that resolve your need?

**Comment by Richienb** [comment]
Like this?

```js
const pThrottle = require('p-throttle');

const now = Date.now();

const throttle = pThrottle({
	limit: 2,
	interval: 1000
});

const throttled = throttle(index => {
	const secDiff = ((Date.now() - now) / 1000).toFixed();
	return Promise.resolve(`${index}: ${secDiff}s`);
}, {
	shouldBypassThrottling(...arguments_) {
		// ...
	}
});

for (let i = 1; i <= 6; i++) {
	throttled(i).then(console.log);
}
```

**Comment by sm2017** [comment]
> @sm2017 Would that resolve your need?

@sindresorhus ABSOLUTLY NO! 

```js
throttled(fn, {bypassThrottling: i === 4});
```

is equal to

```js

if(i === 4){
   fn();
}else{
   throttled(fn);
}

```

Why we should have `bypassThrottling` option? Let me explain why we should have `pThrottle.bypassThrottling`


Consider the following minimal abstract class (I just want to show you an example, in my real case I have an abstract class that consume a queue from RabbitMQ and I need different throttling for different queue )

```
class Consumer{
   static get throttleLimit() {
    return 1; //default throttleLimit
  }

  static get throttleInterval() {
    return 1000; //default throttleInterval
  }

  constructor(ctx) {
    if (this.constructor === Consumer) {
      throw new TypeError('Class "Consumer" cannot be instantiated directly.');
    }

    if (this.run=== undefined) {
      throw new TypeError('runmethod is not implemented');
    }

    // final fn = something
    final throttled = pThrottle(fn, this.throttleLimit, this.throttleInterval);
    //  Listen to rabbit mq and consume a queue
   }
}

class FakeConsumer extends Consumer{
 async run(){
    const cache = await cacheService.find(id);
    if(cache){
        return pThrottle.bypassThrottling(cache); // I want to bypass throttling because the calculation is fast and I want to consume RabbitMQ queue as fast as possible 
    }else{
       const data = await expensiveService.find(id);// I have a rate limit in expensive service, it's a third party service, If I call it too many times I blocked for long time
       await  cacheService.put(id,data);
       return data ;
    }
 }
}
```
