### ISSUE TITLE
Throttled function can exhaust available memory

### ISSUE THREAD

**Issue by jedwards1211** [sindresorhus/p-throttle#2]
Consider what would happen if the throttled function is continuously called more often than the delay:
```js
const foo = throttle(() => {...}, 1000)
setInterval(foo, 10)
```
`p-throttle` would keep queuing up calls faster than it can process them, and eventually the queue would run out of memory.

While it would be ridiculous to set an interval like this, it illustrates the fact `p-throttle`'s memory usage is unbounded.  If a user kept moving the mouse for a long time, and the events were coming in every 10 ms, then browser memory usage would continue to increase as long as the user kept moving the mouse.

`lodash-throttle` doesn't have this problem because it doesn't queue up calls; it just calls the throttled function once with the most recent arguments to `foo` in each window of time.

I'm not sure you intended for the semantics of `p-throttle` to differ so significantly from `lodash-throttle`, which is what devs are probably most familiar with.

If you did intend for this to have an unbounded queue, it would be helpful to warn about potential memory exhaustion to the README.  Otherwise, you might want to make `p-throttle` behave more like `lodash-throttle`.

**Comment by bhj** [comment]
Agreed, perhaps adding a `queueLimit` option would help (I think it should default to `1` to match lodash's behavior but it would be a breaking change)

**Comment by jedwards1211** [comment]
@bhj yes. One more note about matching lodash behavior with a `queueLimit` of 1 though: when the queue is full and the function is called again, it would have to replace the last element in the queue with the latest args, instead of just ignoring it, because `lodash-throttle` always calls the throttled function with the most recent arguments.

**Comment by bhj** [comment]
@jedwards1211 Good call. FWIW this seems to work as expected: https://github.com/jcoreio/async-throttle

**Comment by jedwards1211** [comment]
@bhj Heh, I wrote that package ;)

**Comment by bhj** [comment]
@jedwards1211 Hah didn't catch that from the URL! Well anyway, it's working, thanks 😄

**Comment by sholladay** [comment]
Reading the docs before using it, I was surprised to see that this module queues up function calls. I definitely expected it to only _limit the calls per second_, not _spread the calls out over time_. Very different semantics, which I would personally prefer a separate module for.

**Comment by richardscarrott** [comment]
@sholladay A common scenario whereby you'd want to ensure all calls are eventually run might be whereby the call performs a side effect, e.g. creating 1000 todos without hitting the api limit.
