### ISSUE TITLE
throttle across multiple processes

### ISSUE THREAD

**Issue by jaschaio** [sindresorhus/p-throttle#35]
Any insights how I would do this if I am hitting an API from multiple node processes and thus need to limit the execution across all processes?

**Comment by jaschaio** [comment]
It's probably not the right tool for the job.

My best guess is to use a single redis key across all processes that counts the number of executions and when the limit is reached wait's for a certain time.

See https://redis.io/commands/INCR

**Comment by sindresorhus** [comment]
I would also use Redis for this.
