### ISSUE TITLE
Bizarre behavior with Bluebird

### ISSUE THREAD

**Issue by kaatt** [sindresorhus/p-throttle#4]
I just spent a few hours debugging this so thought it may help someone. When the global Promise object is replaced with bluebird, the async function mysteriously never resolves.

Code to repro:
```js
global.Promise = require('bluebird')
const pThrottle = require('p-throttle')
const got = require('got')

const throttled = pThrottle(got, 1, 1000)

async function main() {
  for (let i = 1; i <= 3; i++) {
    const { headers } = await throttled('http://httpbin.org/response-headers')
    console.log(headers.date)
  }
  console.log('~End~')
}

main().catch(console.error)
```

When Promise is patched, the process just exits with code 0 and even `~End~` is not logged to the console.
When Promise isn't patched, or when `pThrottle` isn't used (just got), then it works as it should.

Tested this with node v8.9.0 and v9.1.0 on macOS and Linux.

**Comment by sindresorhus** [comment]
Sounds like you should open an issue on Bluebird itself as it works fine with the native Promise.

**Comment by kaatt** [comment]
https://github.com/petkaantonov/bluebird/issues/1480

**Comment by kaatt** [comment]
https://github.com/nodejs/node/issues/17278
