### ISSUE TITLE
Use `Performance.now()` instead of `Date.now()`

### ISSUE THREAD

**Issue by dormeiri** [sindresorhus/p-throttle#42]
I see that the package uses `Date.now()` for calculating the delta between the current time and the beginning of the window.

https://github.com/sindresorhus/p-throttle/blob/3dffe707c0061370be8ce0a8c687bd032b6acaef/index.js#L23

https://github.com/sindresorhus/p-throttle/blob/3dffe707c0061370be8ce0a8c687bd032b6acaef/index.js#L44

When calculating times delta it is [recommended](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/High_precision_timing#performance.now_vs._date.now) to use `Performance.now()` as it is monotonic, more precise, and more system agnostic.

WDYT about changing `Date.now()` to `Performance.now()`?

I can open a PR if needed

**Comment by sindresorhus** [comment]
👍

**Comment by dormeiri** [comment]
The build fail after doing it, not worth breaking something so I guess we'll keep `Date.now`. It is not that important anyway
