### ISSUE TITLE
Minor optimization - don't call `setTimeout` if not needed

### ISSUE THREAD

**Issue by dormeiri** [sindresorhus/p-throttle#43]
When `getDelay()` returns `0` there is no need to call `setTimeout`, it creates redundant event-loop event.

https://github.com/sindresorhus/p-throttle/blob/3dffe707c0061370be8ce0a8c687bd032b6acaef/index.js#L83-85

My suggestion:

- Check first if the result of `getDelay()` is greater than `0`
- If yes, run `setTimeout` and insert it to the `queue`.
- Otherwise, run `execute` directly, call `queue.delete(timeoutId);` only if `timeoutId` is defined.

WDYT?

I can open a PR if it helps.

**Comment by sindresorhus** [comment]
👍

I don't think it will help much in real-world situations though, as the bottleneck is IO not the this package or the event-loop.

**Comment by dormeiri** [comment]
I generally agree, however it is more for when there are many events in the event-loop, then the execution start will get delayed.

Here is a PR https://github.com/sindresorhus/p-throttle/pull/46
