### ISSUE TITLE
Add a callback hook when throttled

### ISSUE THREAD

**Issue by dormeiri** [sindresorhus/p-throttle#44]
I would like to observe every time I reach the throttling limit and get delayed.

I think I can achieve it by calling a callback function when `getDelay()` is greater than zero here:

https://github.com/sindresorhus/p-throttle/blob/3dffe707c0061370be8ce0a8c687bd032b6acaef/index.js#L83

The callback function can be passed as one of the options in:

https://github.com/sindresorhus/p-throttle/blob/3dffe707c0061370be8ce0a8c687bd032b6acaef/index.js#L8

I suggest something like this: `onDelay: (info: { delay: number, queueSize: number }) => void | Promise<void>`, WDYT?

I can open a PR if it helps.

**Edit**: I can live without passing the `info` to the callback, so this also works for my use-case: `onDelay: () => void | Promise<void>`

**Comment by sindresorhus** [comment]
What's the use-case?

**Comment by dormeiri** [comment]
I want to send a metric when delayed to analyze the performance.
