### ISSUE TITLE
Publish es5 version

### ISSUE THREAD

**Issue by thasmo** [sindresorhus/p-throttle#5]
Thanks for the awesome throttle implementation. Would you mind also publishing an es5-compatible version to npm? Is this something you would consider doing? It would be nice to get rid of the extra transpilation step.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by thasmo** [comment]
@sindresorhus, thanks for the reply and the additional information. Gonna try it!
