### ISSUE TITLE
TypeScript NodeNext: Cannot import p-throttle without ESM configuration

### ISSUE THREAD

**Issue by knikoletic** [sindresorhus/p-throttle#58]
#### Problem
When trying to import the `p-throttle` package in a TypeScript project using `NodeNext` module resolution, the following error occurs:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("p-throttle")' call instead.
```

The error occurs when using:
```typescript
import pThrottle from "p-throttle";
```

#### Current Workarounds (that we want to avoid)
- Changing `"type": "module"` in package.json
- Using dynamic imports (`import()`)
- Switching to different module resolution strategies

#### Desired Solution
Looking for a clean way to use `p-throttle` with TypeScript's `NodeNext` module resolution without:
- Modifying package.json module type
- Using dynamic imports
- Changing the TypeScript module configuration
- Adding additional build steps

#### Environment
- Package: p-throttle
- TypeScript Configuration:
```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "outDir": "./dist",
    "allowJs": true,
    "jsx": "preserve",
    "skipLibCheck": true
  }
}
```
- Node.js version: 22.11.0
- Package Manager: npm

#### Additional Context
This issue occurs in TypeScript projects using the modern `NodeNext` resolution strategy while trying to import ESM-only packages. The `NodeNext` module resolution should theoretically handle both ESM and CommonJS modules, but seems to struggle with this particular package.

#### Questions
1. Is there a way to use `p-throttle` with `NodeNext` module resolution without configuration changes?
2. Are there TypeScript-friendly alternatives that work with `NodeNext` resolution?
3. Is this a limitation of the package or TypeScript's module resolution?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
