### ISSUE TITLE
Timeout doesn't get cleaned up and prevent Node process to complete

### ISSUE THREAD

**Issue by pvdlg** [sindresorhus/p-throttle#6]
After executing the throttled function at least one timer is left running and prevent the Node process to exit.

The only way to get Node to exit is to use `process.exit()`.

I looked at it but not sure how to fix it. I guess the timeout should not be created pre-emptively.

**Comment by pvdlg** [comment]
Reproduction code:
```js
// File test.js

const pThrottle = require('p-throttle');

const now = Date.now();

const throttled = pThrottle(i => {
	const secDiff = ((Date.now() - now) / 1000).toFixed();
	return Promise.resolve(`${i}: ${secDiff}s`);
}, 10, 5000);

for (let i = 1; i <= 6; i++) {
	throttled(i).then(console.log);
}
```
```bash
node test.js

1: 0s
2: 0s
3: 0s
4: 0s
5: 0s
6: 0s
// Wait 5s then exit
```

**Comment by pvdlg** [comment]
Just to clarify the problem is not that it doesn't exit. The problem is that it waits 2 extra seconds before exiting. This is because `setTimeout` is called pre-emptively, so a timeout is set even if the function will not be called in the future.

I just reproduced with Node 10.10.0. You can increase the interval so it's more visible.

```js
const now = Date.now();
const throttled = pThrottle(
  i => {
    const secDiff = ((Date.now() - now) / 1000).toFixed();
    return Promise.resolve(`${i}: ${secDiff}s`);
  },
  2,
  5000
);

for (let i = 1; i <= 4; i++) {
  throttled(i).then(console.log);
}
```

```
1: 0s
2: 0s
// Wait 5 seconds as expected
3: 5s
4: 5s
// Wait 5 seconds and exit, should exit right away
```

See my terminal recording: https://asciinema.org/a/LvAI2K8BdIWDHD9P638S9pobV

**Comment by szmarczak** [comment]
There was the same issue with `p-queue`: https://github.com/sindresorhus/p-queue/pull/35 I hope I can fix this one too :)
